language: python
sudo: false

git:
  submodules: false

matrix:
  include:
    - os: linux
      python: 3.4
    - os: linux
      python: 3.5
    - os: linux
      python: 3.6
    - os: osx
      language: generic
      env: PYTHON_VERSION=3

addons:
  apt:
    packages:
    - ttf-dejavu

before_install:
  # Pango 1.38+ is needed to make @font-face work, remove these two lines when it's available on Travis
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then mkdir -p ~/.fonts; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget "https://github.com/Kozea/Ahem/blob/master/Ahem.ttf?raw=true" -O ~/.fonts/Ahem.ttf; fi

  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew tap caskroom/fonts; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew pin numpy gdal postgis; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew upgrade python; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cask install font-dejavu-sans; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install cairo pango gdk-pixbuf libffi; fi

install:
  # Needed because of https://github.com/pypa/setuptools/pull/1089
  # Can be removed as soon as setuptools-36.2.0 is not the default version anymore on Travis with Python 3.4
  - pip$PYTHON_VERSION install --upgrade setuptools

script:
  - python$PYTHON_VERSION setup.py test
